// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbblchaedpzgtdxrxkjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiYmxjaGFlZHB6Z3RkeHJ4a2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzY3ODgsImV4cCI6MjA2MjM1Mjc4OH0.KLjY2iTRhdzTQGqIxZaIYN5gePXkfd0c8YL08FeHbNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);